
### Create Project

POST   http://localhost:8080/odata/v4/AdminService/Projects
Content-Type: application/json
Authorization: Basic authenticated:

{"ID": 1 , "content":"assets/global.svg","name":"Demo Project" ,"phases":[{"ID": 1,"content":"assets/phase01.svg","name":"Phase 01"},{"ID": 2,"content":"assets/phase02.svg","name":"Phase 02"},{"ID": 3,"content":"assets/phase03.svg","name":"Phase 03"},{"ID": 4,"content":"assets/phase04.svg","name":"Phase 04"}]}

### Create Phases

Post  http://localhost:8080/odata/v4/AdminService/Populate
Content-Type: application/json
Authorization: Basic authenticated:




        
       



### Export to Table

Post  http://localhost:8080/odata/v4/UserService/SellProperty
Content-Type: application/json
Authorization: Basic authenticated:


{"Property":{
    "MapID":"2",
    "REFX":"REFX2",
    "Status":"sold"
}
}





### Create REFX

Patch projects-service-triumphant-baboon-hl.cfapps.us10-001.hana.ondemand.com/odata/v4/AdminService/MappingTable
Content-Type: application/json
Authorization: Basic authenticated:

    {"MapID":"MAPID","REFX":"REX"}



### Search by MapID

GET  http://localhost:8080/odata/v4/PropertyService/getPropertyByMapID(MapID='14')
Content-Type: application/json
Authorization: Basic authenticated:

{"MapID": "14"}




### Create Categories

Post http://localhost:8080/odata/v4/AdminService/Properties
Content-Type: application/json

{"REFX":"REFXIL",  "MapID":"158","Path": "New.com", "Status": "Available", "Phase_ID":2}



### Export to table function

Get  http://localhost:8080/odata/v4/ExportToTable/ExportToTable()
Content-Type: application/json
Content-Length: ####

{"REFX":"REFX",  "MapID":"155"}


### Create ERP table entry

POST   http://localhost:8080/odata/v4/AdminService/Projects
Content-Type: application/json
Authorization: Basic authenticated:


{"ID": 1 , "content":"content Test", "phases":[{"ID": 1,"content":"Phase Content"},{"ID": 2,"content":"Phase Content"}]}


### Create Erp Table Mass Upload

Post  http://localhost:8080/odata/v4/AdminService/MassUploadMapping
Content-Type: application/json
Authorization: Basic authenticated:

{"Properties":[

        {"REFX":"REFL",  "MapID":"180","Project_ID":1,"Phase_ID":2},

        {"REFX":"REFXID",  "MapID":"1559","Project_ID":1,"Phase_ID":1}

    ]

    }



 

 
    
    
        


