---
spring:
  config.activate.on-profile: default
  sql.init.schema-locations: classpath:schema-h2.sql
  cors:
    allowed-origins: https://edraky-plan-map-demo.web.app/, http://localhost:4200 , http://localhost:8080
    allowed-methods: GET, POST, PUT, DELETE
    allowed-headers: Authorization, Content-Type
    allow-credentials: true
    max-age: 3600
  security:
    user:
      name: anonymous
      password:
cds:
  datasource.auto-config.enabled: false
  sql.supportedLocales: "*"
